version: "3"

services:
  db:
    build: ./db
    environment:
      POSTGRES_DB: full-stack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d full-stack -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nick@nicholasgraf.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8001:80"
    links:
      - db:db
    depends_on:
      - db

  api:
    build: ./api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - pgadmin

  ui:
    build: ./ui
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  db-data:
